apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: cloudchamp
  labels:
    role: db
    env: demo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    role: db